api/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports
from rest_framework import routers


# Local imports
from .views import (
    BrandViewSet, CategoryViewSet, ClothViewSet, ImageViewSet, SizeViewSet, )


# Create your urls here.
router = routers.DefaultRouter()
router.register(r'brand', BrandViewSet)
router.register(r'category', CategoryViewSet)
router.register(r'cloth', ClothViewSet)
router.register(r'image', ImageViewSet)
router.register(r'size', SizeViewSet)

clothes/urls.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf.urls import url


# Third party apps imports


# Local imports
from .views import (
    ClothDetailView, IndexListView, NationalListView, InternationalListView, )

# Create your tests here.


urlpatterns = [
    url(
        r'^national/$',
        NationalListView.as_view(),
        name='national'
    ),
    url(
        r'^international/$',
        InternationalListView.as_view(),
        name='international'
    ),
    url(
        r'^$',
        IndexListView.as_view(),
        name='index'
    ),
    url(
        r'^detail/(?P<slug>[\w-]+)$',
        ClothDetailView.as_view(),
        name='detail'
    ),
]

tienda_hero/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from clothes import urls as clothes_urls
from api.urls import router as api_router


urlpatterns = [
    url(
        r'^grappelli/',
        include('grappelli.urls')
    ),
    url(
        r'^admin/',
        include(admin.site.urls)
    ),
    url(
        r'^',
        include(
            clothes_urls,
            namespace='clothes'
        )
    ),
    url(
        r'^api/',
        include(api_router.urls)
    ),
    url(
        r'^docs/',
        include('rest_framework_swagger.urls')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothes/models.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify


# Third party apps imports
from stdimage import StdImageField


# Local imports
from .choices import (
    GENDER_CHOICES,
)

from .managers import (
    BrandQuerySet,
    CategoryQuerySet,
    ClothesQuerySet,
    SizeQuerySet,
)


# Create your models here.
class Brand(models.Model):

    name = models.CharField(max_length=20, unique=True, verbose_name='Nombre')
    national = models.BooleanField(default=True, verbose_name='Marca nacional')

    objects = BrandQuerySet.as_manager()

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'

    def __unicode__(self):
        return u'{}'.format(self.name)


class Category(models.Model):

    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=1, verbose_name=u'Género')
    name = models.CharField(
        max_length=50, verbose_name=u'Nombre de la Categoría')

    objects = CategoryQuerySet.as_manager()

    class Meta:
        verbose_name = u'Categoría'
        verbose_name_plural = u'Categorías'
        unique_together = ('name', 'gender')

    def __unicode__(self):
        return u'{}'.format(self.name)


def image_path(obj, filename):
    return u'prendas/{}/{}'.format(slugify(obj.name), str(filename))


class Image(models.Model):

    img = StdImageField(
        upload_to=image_path,
        variations={'large': (350, 350), 'thumbnail': (75, 75)},
        verbose_name='Imagen')
    name = models.CharField(max_length=30, unique=True, verbose_name='Nombre')

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = u'Imágenes'

    def __unicode__(self):
        return u'{}'.format(self.name)

    def img_thumbnail(self):
        return u'<img src="{}{}" alt="{}">'.format(
            settings.MEDIA_URL, self.img.thumbnail, self.name
        )

    img_thumbnail.allow_tags = True


class Size(models.Model):

    name = models.CharField(max_length=20, unique=True, verbose_name='Talla')

    objects = SizeQuerySet.as_manager()

    class Meta:
        verbose_name = 'Talla'
        verbose_name_plural = 'Tallas'

    def __unicode__(self):
        return u'{}'.format(self.name)


class Cloth(models.Model):

    available = models.BooleanField(default=True, verbose_name='Disponible')
    brand = models.ForeignKey(
        Brand, on_delete=models.CASCADE, verbose_name='Marca')
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name=u'Categoría')
    description = models.TextField(blank=True, verbose_name=u'Descripción')
    images = models.ManyToManyField(
        Image, verbose_name=u'Imágenes de la prenda')
    name = models.CharField(max_length=50, unique=True, verbose_name='Nombre')
    offer_price = models.PositiveSmallIntegerField(
        blank=True, null=True, verbose_name='Precio de oferta (opcional)')
    price = models.PositiveSmallIntegerField(verbose_name='Precio')
    slug = models.SlugField(editable=False, max_length=50)
    size = models.ManyToManyField(Size, verbose_name='Talla')
    stock = models.PositiveSmallIntegerField(
        verbose_name='Cantidad disponible')

    objects = ClothesQuerySet.as_manager()

    class Meta:
        verbose_name = 'Prenda'
        verbose_name_plural = 'Prendas'

    def __unicode__(self):
        return u'{}'.format(self.name)

    def clean(self):
        if self.offer_price >= self.price:
            raise ValidationError({
                'offer_price': [
                    'El precio de oferta debe ser menor al precio', ]})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Cloth, self).save(*args, **kwargs)

clothes/forms.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django import forms


# Third party apps imports


# Local imports


# Create your models here.

api/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports


# Third party apps imports
from rest_framework import filters
from rest_framework.viewsets import ReadOnlyModelViewSet


# Local imports
from clothes.models import Brand, Category, Cloth, Image, Size
from .serializers import (
    BrandSerializer, CategorySerializer, ClothSerializer, ImageSerializer,
    SizeSerializer, )


# Create your views here.
class BaseViewSet(ReadOnlyModelViewSet):

    filter_backends = (filters.DjangoFilterBackend, )
    http_method_names = [u'get']


class BrandViewSet(BaseViewSet):

    filter_fields = ('national', )
    queryset = Brand.objects.availables()
    serializer_class = BrandSerializer


class CategoryViewSet(BaseViewSet):

    filter_fields = ('gender', )
    queryset = Category.objects.availables()
    serializer_class = CategorySerializer


class ClothViewSet(BaseViewSet):

    filter_fields = ('brand', 'category', 'size')
    queryset = Cloth.objects.availables()
    serializer_class = ClothSerializer


class ImageViewSet(BaseViewSet):

    queryset = Image.objects.all()
    serializer_class = ImageSerializer


class SizeViewSet(BaseViewSet):

    queryset = Size.objects.availables()
    serializer_class = SizeSerializer

clothes/views.py
# -*- coding: utf-8 -*-
# Python imports


# Django imports
from django.views import generic


# Third party apps imports


# Local imports
from .models import Cloth


# Create your views here.
class IndexListView(generic.ListView):
    context_object_name = 'clothes'
    model = Cloth
    paginate_by = 1
    queryset = Cloth.objects.availables()
    template_name = 'clothes/index.html'


class NationalListView(IndexListView):
    queryset = Cloth.objects.nationals()
    template_name = 'clothes/national.html'


class InternationalListView(IndexListView):
    queryset = Cloth.objects.internationals()
    template_name = 'clothes/international.html'


class ClothDetailView(generic.DetailView):
    context_object_name = 'cloth'
    model = Cloth
    template_name = 'clothes/detail.html'

api/templates/api/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ app_name }} index page</title>
  </head>
  <body>
    <h1>{{ app_name }} index page</h1>
  </body>
</html>

clothes/templates/clothes/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>Hero Denim Experience | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
      <ul>
        <li>DENIM</li>
        <li>NIÑOS</li>
      </ul>
      <img alt="Logo Hero Denim" />
    </header>
    {% block navbar %}{% endblock navbar %}
    {% block content %}{% endblock content %}
    <footer> Todos los derechos reservados </footer>
  </body>
</html>

clothes/templates/clothes/detail.html
{% extends 'clothes/base.html' %}
{% load static %}


{% block title %}{{ cloth.name }}{% endblock %}



{% block content %}
<h2>{{ cloth.name }}</h2>
<p>Descripción: {{ cloth.description }}</p>
<p>Marca: {{ cloth.brand }}</p>
{% if cloth.offer_price %}
    <p>Precio de oferta: {{ cloth.offer_price }}</p>
    <strike>Precio normal: {{ cloth.price }}</strike>
{% else %}
    <p>Precio: {{ cloth.price }}</p>
{% endif %}
{% for image in cloth.images.all %}
    <p>Imagen: <img src="{% get_media_prefix %}{{ image.img.large }}" alt="{{ image.img.name }}" /><p>
{% endfor %}
<p>Cantidad: {{ cloth.stock }}</p>
<button onclick="window.history.back()">Atrás</button>
{% endblock %}

clothes/templates/clothes/index.html
{% extends 'clothes/base.html' %}
{% load static %}


{% block title %}Inicio{% endblock %}



{% block navbar %}
{% include 'clothes/partials/_navbar.html' with active_link='clothes:index' %}
{% endblock navbar %}



{% block content %}
<h2>Prendas</h2>
{% for cloth in clothes %}
    <p>{{ cloth.name }}</p>
    <p>Descripción: {{ cloth.description }}</p>
    <p>Marca: {{ cloth.brand }}</p>
    {% if cloth.offer_price %}
        <strike><p>Precio normal: {{ cloth.price }}</p></strike>
        <p>Precio de oferta: {{ cloth.offer_price }}</p>
    {% else %}
        <p>{{ cloth.price }}</p>
    {% endif %}
    {% for image in cloth.images.all %}
        <img src="{% get_media_prefix %}{{ image.img.large }}" alt="{{ image.img.name }}" />
    {% endfor %}
    {% ifequal cloth.stock 0  %}
      <p>Cantidad: Actualmente sin stock</p>
    {% else %}
      <p>Cantidad: {{ cloth.stock }}</p>
    {% endifequal %}
    <a href="{% url 'clothes:detail' cloth.slug %}">Ver detalle</a>
{% endfor %}

{% if is_paginated %}
    <ul>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}
        {% for page in page_obj.paginator.page_range %}
            {% ifequal page_obj.number page  %}
                <li><span>{{ page }}</span></li>
            {% else %}
                <li><span><a href="?page={{ page }}">{{ page }}</a></span></li>
            {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
        {% endif %}
    </ul>
{% endif %}
{% endblock content %}

clothes/templates/clothes/international.html
{% extends 'clothes/index.html' %}



{% block title %}Prendas Importadas{% endblock %}



{% block navbar %}
{% include 'clothes/partials/_navbar.html' with active_link='clothes:international' %}
{% endblock navbar %}

clothes/templates/clothes/national.html
{% extends 'clothes/index.html' %}



{% block title %}Prendas Nacionales{% endblock %}



{% block navbar %}
{% include 'clothes/partials/_navbar.html' with active_link='clothes:national' %}
{% endblock navbar %}

clothes/templates/clothes/partials/_navbar.html
<ul>
    <li{% ifequal active_link 'clothes:index' %} class="active"{% endifequal %}><a href="{% url 'clothes:index' %}">Índice</a></li>
    <li{% ifequal active_link 'clothes:national' %} class="active"{% endifequal %}><a href="{% url 'clothes:national' %}">Prendas Nacionales</a></li>
    <li{% ifequal active_link 'clothes:international' %} class="active"{% endifequal %}><a href="{% url 'clothes:international' %}">Prendas Importadas</a></li>
</ul>